# Generated by Django 3.1 on 2023-02-10 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('company', models.CharField(max_length=255, verbose_name='Компания')),
                ('logo', models.CharField(max_length=500, verbose_name='Логотип компании (Ссылка на изображение)')),
                ('postDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время публикации')),
                ('isActive', models.BooleanField(default=True, verbose_name='Активная/В архиве')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('linkJob', models.CharField(max_length=500, verbose_name='Ссылка на вакансию')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('company', models.CharField(max_length=255, verbose_name='Компания')),
                ('logo', models.CharField(max_length=500, verbose_name='Логотип компании (Ссылка на изображение)')),
                ('postDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время публикации')),
                ('isActive', models.BooleanField(default=True, verbose_name='Активная/В архиве')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('linkCompany', models.CharField(max_length=500, verbose_name='Ссылка на сайт компании')),
            ],
            options={
                'verbose_name': 'Производственная практика',
                'verbose_name_plural': 'Производственные практики',
            },
        ),
    ]
